export default Object.freeze({
    LOGIN: "/login",
    SIGN_UP: "/sign-up",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    HOME: "/home",
    REPORTS: "/reports",
    NEW_REPORT: "/new-report",
    CONTACTS: "/contacts",
    PATIENT_ACCOUNT: "/patient-account",
    DOCTOR_ACCOUNT: "/doctor-account",
    RECOMMENDATIONS: "/recommendations",
    GRAPHS: "/graphs",
    PATIENTS: "/patients",
    SEARCH_PATIENTS: "/search-patients",
    MEDICAL_CENTERS: "/medical-centers",
});